# api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  selector:
    app: my-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30001
  type: NodePort
